[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Explore"
LANDING_DESCRIPTION = "This is my class on DevOps. Concepts and files of knowledge are organized in an (unstructured) inter-linked knowledge graph."
LANDING_PAGE = "home"
LANDING_TITLE = "Welcome!"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/ZiggerZZ/obsidian-pkm"
SITE_TITLE = "Zigfrid's class on DevOps"
SITE_URL = "https://competent-benz-84ccf2.netlify.app/"
TIMEZONE = "Europe/Paris"
ZOLA_VERSION = "0.15.2"
